/* github.js
   Reads /data/github_data.json (generated by scripts/fetch_data.py via GitHub Actions)
   and updates:
     - #gh-repo-count   → total public repos
     - #gh-recent       → list of recent pushes
     - #gh-updated      → "last synced X minutes ago"
*/

document.addEventListener('DOMContentLoaded', () => {
  const repoCountEl  = document.getElementById('gh-repo-count');
  const recentEl     = document.getElementById('gh-recent');
  const updatedEl    = document.getElementById('gh-updated');

  if (!repoCountEl && !recentEl) return;   // elements not on this page

  fetch('/data/github_data.json')
    .then(r => r.ok ? r.json() : Promise.reject(r.status))
    .then(data => {
      // Repo count
      if (repoCountEl && data.public_repo_count > 0) {
        repoCountEl.textContent = data.public_repo_count;
      }

      // Last synced
      if (updatedEl && data.generated_at && data.generated_at !== 'pending first run') {
        const diff = Math.round((Date.now() - new Date(data.generated_at)) / 60000);
        updatedEl.textContent = diff < 60
          ? `synced ${diff}m ago`
          : diff < 1440
          ? `synced ${Math.round(diff / 60)}h ago`
          : `synced ${Math.round(diff / 1440)}d ago`;
      }

      // Recent pushes list
      if (recentEl && Array.isArray(data.recent_pushes) && data.recent_pushes.length) {
        const timeAgo = iso => {
          const m = Math.round((Date.now() - new Date(iso)) / 60000);
          if (m < 60)   return m + 'm ago';
          if (m < 1440) return Math.round(m / 60) + 'h ago';
          return Math.round(m / 1440) + 'd ago';
        };

        recentEl.innerHTML = data.recent_pushes.map(r => `
          <div class="gh-row">
            <a class="gh-name" href="${r.html_url}" target="_blank" rel="noopener">${r.name}</a>
            ${r.language ? `<span class="gh-lang">${r.language}</span>` : ''}
            <span class="gh-time">${timeAgo(r.pushed_at)}</span>
          </div>
        `).join('');
      }
    })
    .catch(() => {
      // Silently fail — static fallback text already in HTML
    });
});
